# Generated by Django 5.2.7 on 2025-11-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_attachment_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='category',
        ),
    ]
